replicas: 5
memoryrequest: 12G
kafkaopts: "-Dlogging.level=INFO -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
javaopts: "-Xmx6G -Xms6G"
cpurequest: 4
storagesize: 1Gi
zookeeperconnectionstring: zk-cs.zk.svc.cluster.local:2181
image: gcr.io/google_containers/kubernetes-kafka:1.0-10.2.1
datadogapikey: NOT_SET
