apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{.namespace}}
  labels:
    app: kafka
spec:
  ports:
  - port: 9999
    name: tcp-jmx
  - port: 7004
    name: tcp-server
  selector:
    app: kafka
